[package]
name = "chemformula"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["chemistry", "parsing", "chemical formulas"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
nalgebra = "0.32.*"
